relooking de la page main
HuanJY/SAES4 pull request #22
Opened 2024-05-30 17:04 UTC by HuanJY

2024-05-30 21:08 UTC, Bafy78 requested changes
Je pense que les boutons "Se connecter" et "Créer un compte" devrait être l'un à gauche de l'autre, parce que là sur mon écran y en a un qui déborde en haut et l'autre en bas. Ou alors il faut changer la hauteur du bandeau.

2024-05-30 23:08 UTC, HuanJY commented
Boutons côte à côte

2024-05-31 09:51 UTC, Bafy78 requested changes
Pas mal mais il faudrait une image du thème en fond d'écran de la page Login

2024-05-31 09:59 UTC, Bafy78 commented
faudrait retirer le bouton mot de passe oublié, ou alors que quand on clique dessus il te dises "haha le loser"

2024-05-31 16:45 UTC, Bafy78 approved these changes

2024-05-31 16:46 UTC, merged